### ISSUE TITLE
Console Error when using the package mode

### ISSUE THREAD

**Issue by ajmaurya99** [10up/10up-toolkit#109]
**Describe the bug**
I am getting a Console Error when using the package mode, I.e when I use main/source in my package.json
eg - 
```
  "main": "dist/simple-local-avatars.js",
   "source": "./simple-local-avatars.dev.js",
```

**Steps to Reproduce**

1. Install the https://github.com/10up/10up-toolkit package.
2. Add the main/source in your package.json
3. Run `10up-toolkit build` 
4. Then open the console and you should get an Error - `Uncaught ReferenceError: module is not defined`

My `package.json` file

```
{
    "name": "simple-local-avatars",
    "version": "2.2.0",
    "description": "Adds an avatar upload field to user profiles. Generates requested sizes on demand just like Gravatar!",
    "main": "dist/simple-local-avatars.js",
    "source": "./simple-local-avatars.dev.js",
    "scripts": {
        "start": "10up-toolkit start",
        "build": "10up-toolkit build",
        "format:js": "10up-toolkit format-js",
        "lint:js": "10up-toolkit lint-js",
        "lint:css": "10up-toolkit lint-style"
    },
    "repository": {
        "type": "git",
        "url": "git@github.com:10up/simple-local-avatars.git"
    },
    "author": "10up",
    "license": "GNU General Public License v2.0",
    "devDependencies": {
        "10up-toolkit": "^1.0.12",
        "@wordpress/scripts": "^18.0.1"
    },
    "eslintConfig": {
        "extends": "@10up/eslint-config"
    },
    "stylelint": {
        "extends": "@10up/stylelint-config"
    },
    "dependencies": {
        "regenerator-runtime": "^0.13.9"
    }
}

```

**Expected behavior**
No errors in console tab.

**Screenshots**

<img width="1792" alt="Screenshot 2021-10-05 at 10 21 16 PM" src="https://user-images.githubusercontent.com/9847340/136069267-e907fda2-bc2a-4dde-b802-acb9d10c2060.png">
<img width="649" alt="Screenshot 2021-10-05 at 10 21 27 PM" src="https://user-images.githubusercontent.com/9847340/136069279-7d0fa457-81dd-466a-a1d2-c6eef0a7ab50.png">

**Environment information**
 - Device: MacBook
 - OS: MacOS 11.6
 - Browser and version: Chrome 94.0.4606.61
 - WordPress version: 5.8.1

**Additional context**

**Comment by nicholasio** [comment]
Thanks for the report! I'll have a look into this issue.

**Comment by nicholasio** [comment]
Do you still get this issue if you do `10up-toolkit build -f=commonjs`?

I've just set up a  new project with package mode and I'm not getting this console error.

**Comment by ajmaurya99** [comment]
I'll try to test this tomorrow morning and update accordingly.

**Comment by thrijith** [comment]
I've tried the above command and it didn't work, tested with latest version as well.

**Comment by nicholasio** [comment]
I'm going to close this as haven't been able to replicate this issue. Additionally, `10up-toolkit` cannot coexist with `@wordpress/scripts` and it seems @ajmaurya99 had both when trying this out.

```
    "devDependencies": {
        "10up-toolkit": "^1.0.12",
        "@wordpress/scripts": "^18.0.1"
    },
    
```

**Comment by nicholasio** [comment]
Looks like this is still happening, reopening

**Comment by nicholasio** [comment]
Ok so this is finally "fixed" here: https://github.com/10up/10up-toolkit/pull/244

Package mode by default requires the package to be consumed by a bundler.

If you're using package mode for simplicity sake but are shipping the bundled code directly to a browser  you can now use `--format-none`.

```
10up-toolkit build --format=none
```

That way toolkit will no longer instrument the code for inclusion by other bundlers.
