### ISSUE TITLE
Migrate from deprecated `stylelint-declaration-use-variable` to `stylelint-declaration-strict-value`

### ISSUE THREAD

**Issue by ian-pvd** [10up/10up-toolkit#122]
This suggestion is a follow up to a question asked here: https://github.com/10up/10up-toolkit/pull/119#issuecomment-984878438

**Is your enhancement related to a problem? Please describe.**
The stylelint plugin `stylelint-declaration-use-variable` is [deprecated](https://github.com/sh-waqar/stylelint-declaration-use-variable#stylelint-declaration-use-variable). This plugin is reverenced [here](https://github.com/10up/10up-toolkit/blob/e6754a38ceccfc3bc6b9050a5d33b1406811e121/packages/stylelint-config/index.js#L3) and [here](https://github.com/10up/10up-toolkit/blob/bbb2b003486f19ee6dd99dbf28d2d0eae1a20a3f/packages/stylelint-config/package.json#L37).

**Describe the solution you'd like**
The deprecated plugin should be replaced with a new plugin called `stylelint-declaration-strict-value` which was written to replace the deprecated plugin. It includes some new config features, and is written using ES6 which presumably means it'd be more performant.

**Describe alternatives you've considered**
`stylelint-declaration-use-variable` works for now, so this issue could be ignored until there is a conflict with node versions or another build module.

**Additional context**
I added `stylelint-declaration-strict-value` to a personal project and I've found it easy to use.

**Comment by nicholasio** [comment]
This all makes sense! Feel free to submit a PR :)
