### ISSUE TITLE
How to copy over font directory that includes .css files?

### ISSUE THREAD

**Issue by rossberenson** [10up/10up-toolkit#128]
Hi,

I use fonts from typography.com. When the project is set to Production mode, typogrpahy.com provides a css file to load in the header / enqueue. This css file is hosted on their server. The contents of the css file are imports, that import the font files from the website's server. In addition to `.eot` files, there are necessary `.css` files. These css files include the font as a base64. 

<img width="221" alt="Screen Shot 2022-01-13 at 11 54 15 AM" src="https://user-images.githubusercontent.com/2307364/149373899-6aec4417-2af9-493b-a75e-15aa4174b51a.png">

In the past, I would have webpack copy the whole `/font` directory to `/dist`. 10up Toolkit, already kinda does that but only copies font files. That makes sense, cause normally, that's all you'd have in a `/font` directory. I don't want to modify 10up code to accomplish this. I've also been trying to add some webpack config to my theme but having difficulty with having that work with the 10up Toolkit. No fault of 10up, I just might not understand how it works as well as I should.

Any help would be appreciated, I wish typography.com worked like typekit and google fonts! 

Thanks!

**Comment by nicholasio** [comment]
@rossberenson How are these CSS files loaded? There's a PR open to also include copying .otf files. https://github.com/10up/10up-toolkit/pull/133/files

Additionally, you can extend the webpack config yourself to make the necessary changes.

https://github.com/10up/10up-toolkit/blob/develop/packages/toolkit/README.md#customizing-the-webpack-config

**Comment by rossberenson** [comment]
I never saw the notification for your comment, @nicholasio! Sorry about that. Not sure why I haven't. 

I recently came across the readme that you linked me to. I haven't had a moment to give it a go, yet. 

For your information. The .css files are loaded from a remote .css file. https://cloud.typography.com/***/**/css/fonts.css. This css has various imports. Typography knows where the .css files exist because you specify the location on their end. 

So, the .css files in the screenshot above, need to live in a certain location. In this case, since they are fonts, I have them in the `fonts/`. I'll try to modify the webpack config to copy the .css files within the font directory. It's an odd request but this is sadly how typography.com works.

**Comment by nicholasio** [comment]
Looks like you just need to tell webpack to copy additional files.

You can try something like this:

Place this in the root of your theme or plugin
```javascript
// webpack.config.js
const config = require('10up-toolkit/config/webpack.config.js');

// If eslint throws errors saying copy-webpack-plugin is not in devDeps
// eslint-config-disable-next-line
const CopyPlugin = require('copy-webpack-plugin');

config.plugins.push(new CopyPlugin({
			patterns: [
				{ from: 'path-to-font/*.css', to: 'dist/font' , noErrorOnMissing: true, },
			],
		}));

 module.exports = config;
```

**Comment by rossberenson** [comment]
Thanks @nicholasio , will give it a shot.

**Comment by rossberenson** [comment]
Got it going. Thank you, @nicholasio!

For anyone else in a similar situation, here's the code that worked for my setup. 
`rootTheme/assets/fonts/fontNameOrID/fontOne.css`, `rootTheme/assets/fonts/fontNameOrID/fontTwo.css`

```
// webpack.config.js
const config = require('10up-toolkit/config/webpack.config');

// If eslint throws errors saying copy-webpack-plugin is not in devDeps
// eslint-disable-next-line import/no-extraneous-dependencies
const CopyWebpackPlugin = require('copy-webpack-plugin');

config.plugins.push(
	new CopyWebpackPlugin({
		patterns: [
			{
				from: 'fonts/**/*.css',
				to: '[path]/[name].css',
				context: 'assets/',
				noErrorOnMissing: true,
			},
		],
	}),
);

module.exports = config;
```

Output:
`rootTheme/dist/fonts/fontNameOrID/fontOne.css`, `rootTheme/dist/fonts/fontNameOrID/fontTwo.css`
