### ISSUE TITLE
Wrong `.nvmrc` on toolkit

### ISSUE THREAD

**Issue by Antonio-Laguna** [10up/10up-toolkit#134]
### Describe the bug

Current `.nvmrc` is pinned to version 14 of Node which is the previous LTS -> Fermium.

Fermium is locked to NPM 6. However current `package-lock.json` is version 2 which was introduced with NPM 7 which belongs to Node >= 16 (Gallium).

Either we downgrade the package-lock to be compatible with Node 14 or we bump the `.nvmrc` to 16.

### Steps to Reproduce

1. Clone the repo
2. `cd` into it and type `nvm use`
3. You should get a message similar to `Now using node v14.19.0 (npm v6.14.15)`
4. Try to run `npm i`
5. You now get this message: 

```bash
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, 
but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nicholasio** [comment]
We should update to node 16. I'd even add npm >= 7 in package.json.
