### ISSUE TITLE
Abandoning Lerna

### ISSUE THREAD

**Issue by Antonio-Laguna** [10up/10up-toolkit#152]
How would you feel about abandoning Lerna? Lerna is dead and I don't think we should tie ourselves into it. 

I'd say we could leverage [NPM Workspaces](https://docs.npmjs.com/cli/v7/using-npm/workspaces) and would be open to submitting a PR.

It kind of spawns from #144, not sure if other repo tools could help here (would think they do) but I'm open to anything :)

**Comment by nicholasio** [comment]
@Antonio-Laguna I agree with moving away from lerna, however I'm using `lerna version` for handling the publishing workflow and it's been working fine.

Perhaps in the short term we can stop using lerna to resolve local packages and use npm workspaces instead. Then in the future we can look into other options to handle publishing the packages.

**Comment by Antonio-Laguna** [comment]
What does lerna version?

**Comment by nicholasio** [comment]
> What does lerna version?

https://github.com/lerna/lerna/tree/main/commands/version

**Comment by nicholasio** [comment]
One alternative is to integrate https://github.com/changesets/changesets to handle changelogs + releases.

**Comment by Antonio-Laguna** [comment]
This is obviously your prerogative since you're doing this.

I've been managing https://github.com/csstools/postcss-plugins which has (to date) 33 packages and what I can see that lerna does (except for the CHANGELOG) is a combination of:

```bash
$ npm publish --dry-run --workspace $WORKSPACE_NAME
$ npm publish patch|minor|major --workspace $WORKSPACE_NAME
$ npm publish --workspace $WORKSPACE_NAME
```

Which is obviously less intuitive. `changeset` feels nice!

**Comment by nicholasio** [comment]
@Antonio-Laguna how do you handle linked packages? One additional thing that Lerna does is automatically bump the version of all packages that use a package that had a version bump (this is mainly why I was thinking about changeset)

**Comment by Antonio-Laguna** [comment]
@nicholasio isn't that what we're trying to avoid?  Tightly coupling the versions to whatever is on `develop` sounds like a bad idea to me. 

Most of the time, if dependencies are right, we just get fixes and minors with just installing again since they're in range.

Let's pick `@10up/babel-preset-default` which right now stands at version `2.0.0` on which `@10up/toolkit` depends. Say tomorrow you discover that there was a bug and you want to release `2.0.1` to fix that bug. 
`@10up/toolkit` shouldn't need a version bump nor a release since the `^2.0.0` range will just pick `>=2.0.0 <3.0.0` automatically on any new `npm i` (wouldn't on `npm ci`).

I think this leads to fewer chores moving forward. I think though that at times is fine to bump dependencies so they contain, at least, the latest one at the time of upgrade. The key _feature_ is not to have to publish a bunch of packages any time you want to touch a single one.
