### ISSUE TITLE
Provide ability for custom webpack configuration

### ISSUE THREAD

**Issue by kmcaloon** [10up/10up-toolkit#185]
### Is your enhancement related to a problem? Please describe.

I know it could create complications, but I was wondering if there were plans for allowing devs to extend/customize the  webpack configuration by leveraging something like `webpack-merge`. I noticed that a couple of people had questions about customizing their configs (ie #174, #25). In the long run using flags might not be the best as there could be requests for more and more options to be added. Also, for my specific use case I would like to customize the `entry` with a function, and I'm sure other devs would appreciate the flexibility to modify webpack according to specific needs.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nicholasio** [comment]
@kmcaloon It is already possible to extend the webpack config.

At the top of your project you can create a `webpack.config.js` and do something like:

```js
const config = require('10up-toolkit/config/webpack.config');

// mutate the config.

module.exports = config;
```

We don't provide any utility out of the box to help with merging/mutating config but you could always install webpack-merge yourself

In general it would be great to provide enough options that would reduce the need for customizing the config as it becomes easier to break webpack between updates but we understand that it is something necessary in some cases.

**Comment by kmcaloon** [comment]
Thanks @nicholasio I didn't realize `10up-toolkit build` could use our own webpack config. Thanks!
