### ISSUE TITLE
Custom postcss-purgecss not working

### ISSUE THREAD

**Issue by kmcaloon** [10up/10up-toolkit#198]
### Describe your question

Not too sure what is going wrong here. I set up custom `postcss.config.js` with some purgecss settings and they don't seem to be working. Here is the code:

```
module.exports = ( props ) => ( {
  plugins: {
    autoprefixer: {
      add: true,
    },
    ...process.env.NODE_ENV === 'development' ? {} : {
      '@fullhuman/postcss-purgecss': {
        content: [
          './*.php',
          './src/**/*.php',
          // './lib/**/*.php',
          './page-templates/**/*.php',
          './woocommerce/**/*.php',
          './src/**/*.js',
          './src/**/*.jsx',
        ],
        safelist: {
          greedy: [
            /is-/,
            /ra-/,
            /align*/,
            /float/,
            /^i/,
          ],
          deep: [
            /.*olark*/,
            /table/,
            /Cart/,
            /woocommerce/,
            /wp-/,
            /slick/,
          ],
          standard: [ 'srt', /bg-*/, /.!important*/ ],
        },
        extractors: [ {
          extractor: customExtractor,
          extensions: [ 'php', 'js' ],
        } ],
      },
      cssnano: {
        preset: [ 'default', {} ],
      },
    },
  },
} );
```

After running `10up-toolkit build` it seems like nothing is being purged from my stylesheets. I ran some tests where I am able to successfully console.log the correct node environment from the file, so it looks like the file is being processed during build. Just not quite sure why the styles aren't being purged. I'll continue to troubleshoot but wanted to see if I'm missing something obvious here.

Thanks

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kmcaloon** [comment]
Looks like I needed to add `postcss-loader` to my module rules in my custom webpack config. Is this normal? When reading the documentation I assumed the loader was used by default and that my custom `postcss.config.js` would work out of the box.

**Comment by nicholasio** [comment]
We only only use the `postcss-loader` for .css files., maybe that's why it isn't reading the php and js files? Did you had to add postcss-loader to be executed on .php files as well?

I don't have experience with the particular plugin you're using. Can you show your custom webpack.config.js file?

**Comment by Firestorm980** [comment]
@kmcaloon @nicholasio I've used this on a few of our projects internally and haven't had any issues integrating thus far, or having to add any extra packages. I'm currently using it on a project with version 3.1.2 of toolkit. Here's a code sample of a postcss.config.js I have active on a project:

```js
const path = require('path');
const purgecssWordpress = require('purgecss-with-wordpress');

module.exports = ({ file, env }) => {
	const config = {
		plugins: {
			'postcss-import': {},
			'postcss-mixins': {},
			'postcss-preset-env': {
				stage: 0,
				autoprefixer: {
					grid: true,
				},
				features: {
					'custom-properties': false,
				},
			},
		},
	};

	// Only load postcss-editor-styles plugin when we're processing the editor-style-overrides.css file.
	if (path.basename(file) === 'editor-style-overrides.css') {
		config.plugins['postcss-editor-styles'] = {
			scopeTo: '.editor-styles-wrapper',
			ignore: [':root', '.edit-post-visual-editor.editor-styles-wrapper', '.wp-toolbar'],
			remove: ['html', ':disabled', '[readonly]', '[disabled]'],
			tags: ['button', 'input', 'label', 'select', 'textarea', 'form'],
		};
	}

	if (
		env === 'production' &&
		path.basename(file) !== 'editor-style-overrides.css' &&
		!file.includes('/includes/blocks/')
	) {
		config.plugins['@fullhuman/postcss-purgecss'] = {
			content: [
				'./*.php',
				'./assets/js/**/*.js',
				'./includes/**/*.php',
				'./includes/**/*.html', // Block pattern templates
				'./partials/**/*.php',
				'./templates/**/*.php',
			],
			safelist: [
				...purgecssWordpress.safelist,
				'alignwide',
				'alignfull',
				'figcaption',
				/^carousel(-.*)?$/,
				/^sliding(-.*)?$/,
			],
		};
	}

	config.plugins.cssnano =
		env === 'production'
			? {
					preset: [
						'default',
						{
							autoprefixer: false,
							calc: {
								precision: 8,
							},
							convertValues: true,
							discardComments: {
								removeAll: true,
							},
							mergeLonghand: false,
							zindex: false,
						},
					],
			  }
			: false;

	return config;
};
```

@kmcaloon I'm assuming you're on the latest version of toolkit? I may have to try that locally to see if I can recreate the issue if I can get a spare moment.

**Comment by kmcaloon** [comment]
Thanks @nicholasio and @Firestorm980. Yes I am using the latest version. Looks like my issue was that I was using scss and postcss isn't set up as a loader for sass by default. I wanted to use it mostly for purging and autoprefixing. Do you think it should be included by default?

**Comment by nicholasio** [comment]
I'm not sure it would make sense to set up postcss as a loader for sass.

**Comment by kmcaloon** [comment]
@nicholasio so I think it's somewhat common to combine them so as to leverage postcss tooling after the sass compiles to css (ie in this case autoprefixer and purgecss).

**Comment by Firestorm980** [comment]
@kmcaloon I'd agree with the previous comment about it being used in both workflows.

I'm not sure how I feel about it being default, particularly because it isn't _too_ difficult to add on for a per project basis. I worry that it could have a high chance of breaking legacy builds were we utilize that feature. 

@nicholasio Curious what your opinion is on this. I can see this being useful for the wider community. At the very least, maybe we add some example documentation for projects that need that support?

**Comment by nicholasio** [comment]
@Antonio-Laguna Any thoughts on this?

**Comment by Antonio-Laguna** [comment]
@nicholasio I'd say that as long as PostCSS runs after Sass has finished it should be OK. I think it does make sense to enable it in general given that PostCSS and preset-env offer lots of things that you could use on Sass too but Sass has no business doing such as all of the new color work we poured into preset-env or new functions.

**Comment by nicholasio** [comment]
Sounds good! It sounds like there's a valid used case for this then so I'm fine making the change!
