### ISSUE TITLE
Update to use the latest @wordpress/stylelint-config. 

### ISSUE THREAD

**Issue by rossberenson** [10up/10up-toolkit#22]
[stylelint-config-wordpress](https://github.com/WordPress-Coding-Standards/stylelint-config-wordpress) has been deprecated. The latest stylelint config is [@wordpress/stylelint-config](https://www.npmjs.com/package/@wordpress/stylelint-config)

https://developer.wordpress.org/block-editor/reference-guides/packages/packages-stylelint-config/

**Comment by nicholasio** [comment]
This has already been updated. Closing this ticket.
