### ISSUE TITLE
Ensure mixins can be written without being flagged by stylelint

### ISSUE THREAD

**Issue by Antonio-Laguna** [10up/10up-toolkit#226]
### Is your enhancement related to a problem? Please describe.

Given toolkit supports mixins, it should be possible to write them:

```pcss
@define-mixin container {
	padding-left: var(--spacing-04);
	padding-right: var(--spacing-04);

	@media (--bp-min) {
		padding-left: 0;
		padding-right: 0;
	}
}

.entry-content {

	@mixin container;
}
```

It does show: 

```bash
1:1   ✖  Unexpected unknown at-rule "@define-mixin"  scss/at-rule-no-unknown 
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nicholasio** [comment]
@Antonio-Laguna to confirm if this is still an issue.
