### ISSUE TITLE
Using SCSS/Sass instead of PostCSS

### ISSUE THREAD

**Issue by tahireu** [10up/10up-toolkit#228]
### Describe your question

I am using [10up starter theme](https://github.com/10up/wp-scaffold/tree/trunk/themes/10up-theme) for a project, which relies on 10up toolkit package. 

What would be the recommended way to switch from PostCSS to SCSS/Sass?

- In the documentation I see there is a built-in support for Sass
- In the [10up-toolkit/packages/toolkit/config/webpack/modules.js#L99](https://github.com/10up/10up-toolkit/blob/develop/packages/toolkit/config/webpack/modules.js#L99) I see `sass` loader will automatically be used for `scss|sass` files
- When I change extension of my files to `.scss`, files do get compiled, but I still cannot use some SCSS/Sass features such as variables inside of mixins, `#{$i}` type of variables inside `@for` loops etc.
- Compiling still goes through the PostCSS so I usually get errors related to PostCSS and its plugins, such as: 

> postcss-advanced-variables: Could not resolve the variable "$icon"  (used inside the mixin:  [at]include button($icon: "arrow-right");) <

>  postcss-import Unknown word (h#{$i}) <

Thank you!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Antonio-Laguna** [comment]
@tahireu thanks for bringing this up, this is sort of related to https://github.com/10up/10up-toolkit/issues/198

I'm going to work on it this week, and we'll keep you posted!

Basically PostCSS is running before and it's choking on Sass syntax
