### ISSUE TITLE
.asset.php files for css files

### ISSUE THREAD

**Issue by nicholasio** [10up/10up-toolkit#240]
### Describe the bug

Apparently at some point 10up-toolkit was generating `.asset.php` files. The main usecase is simply leveraging `version` for cache bursting (instead of alternatives like `filemtime`.

I'm also not sure if there's a way to generate .asset.php files for css files that are imported through JS.

### Steps to Reproduce

- Add css entry points in `package.json`
- Run build or wath.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nicholasio** [comment]
As far as I can tell, 10up-toolkit is generating the .asset.php for css entry points, it just isn't doing so for CSS that's imported from JS which could just re-use the .asset.php from the js file itself.

@fabiankaegy Thoughts? you think we can close this?

**Comment by fabiankaegy** [comment]
@nicholasio yeah that is what I see also. Which is fine. Closing 👍
