### ISSUE TITLE
Node 18 support

### ISSUE THREAD

**Issue by nicholasio** [10up/10up-toolkit#246]
### Is your enhancement related to a problem? Please describe.

Make sure 10up-toolkit is compatible with no 18.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tobeycodes** [comment]
```
npm ERR! code EBADENGINE
npm ERR! engine Unsupported engine
npm ERR! engine Not compatible with your version of node/npm: eslint-plugin-jsdoc@37.9.7
npm ERR! notsup Not compatible with your version of node/npm: eslint-plugin-jsdoc@37.9.7
npm ERR! notsup Required: {"node":"^12 || ^14 || ^16 || ^17"}
npm ERR! notsup Actual:   {"npm":"8.19.2","node":"v18.12.0"}
```

**Comment by Antonio-Laguna** [comment]
For anyone that comes here, for now, you can do this within your `package.json`

```js
  "overrides": {
    "eslint-plugin-jsdoc": "^39.4.0"
  },
```

We need this PR https://github.com/WordPress/gutenberg/pull/42656 to be merged to actually get support for Node 18.

@fabiankaegy would it be worth spinning up our own PR? Happy to do that if so but I don't want to dismiss the original effort.
