### ISSUE TITLE
Add Webpack Bundle Analyzer

### ISSUE THREAD

**Issue by nicholasio** [10up/10up-toolkit#25]
**Is your enhancement related to a problem? Please describe.**

Add Webpack Bundle Analyzer to help visualize bundle size.

Look into mark-loader as well: https://nolanlawson.com/2021/02/23/javascript-performance-beyond-bundle-size/

**Describe the solution you'd like**

**Designs**

**Describe alternatives you've considered**

**Additional context**

**Comment by Sidsector9** [comment]
Hi @nicholasio, I would like to pick this up.

I've looked into mark-loader as well and it looks useful.
Once both are implemented, should they run by default in production mode or should they it run conditionally based on flags for example `--analyze --mark`?

**Comment by nicholasio** [comment]
@Sidsector9 should definitely be based on a flag, these tools slow down the build considerably. Those flags look good to me. 

So the usage would be something like: `10up-toolkit build --analyze`

**Comment by nicholasio** [comment]
After looking at the mark-loader it's quite old and hasn't been updated so I decided to only include `webpack-bundle-analyzer` for now.
