### ISSUE TITLE
Blocks: editor.css and related source map is only generated if the entry name contains the string 'block'

### ISSUE THREAD

**Issue by roseg43** [10up/10up-toolkit#264]
### Describe the bug

When running `10uptoolkit build` or `10uptoolkit watch`, if the key for an entry doesn't contain the string `block` then crucial block assets aren't generated. Instead of generating `dist/blocks/blockname/editor.css`, a file is created in `dist/css` with the entry key as the filename.

I expect that regardless of what the key is named, if the entry point path contains the block directory as set in `paths.config.js` then the appropriate assets are generated.

If the current behavior is intended, this should be documented clearly in the package readme.

### Steps to Reproduce

1. Create a basic block `example` in a project using 10up-toolkit that imports a CSS file in `block/index.js`
2. In `package.json`, create an entry for your new block, making sure not to include the string `block` in the entry key
3. Run `10uptoolkit build` or `10uptoolkit watch`
4. Observe that the contents of the previously imported CSS file are now in `dist/css/example.css` instead of `dist/blocks/example/editor.css`

### Screenshots, screen recording, code snippet

**Example entry**
`"image-carousel": "./includes/blocks/image-carousel/index.js",`

### Environment information

Using 10up-toolkit `v4.3.1`

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by fabiankaegy** [comment]
@roseg43 yeah the current default behavior of toolkit isn't great with how it handles block assets. Because of that reason we've introduced a new menachanism in 4.2 which greatly improves how block assets are handled. 

You can refer to these docs here: https://github.com/10up/10up-toolkit/blob/develop/packages/toolkit/README.md#wordpress-block-asset-handling

Happy to also jump on a quick call tomorrow to look through this together :)

**Comment by roseg43** [comment]
@fabiankaegy I saw that! I love that we're simplifying the process, but I think we still need a bit in the way of documentation. It doesn't look like we have an explanation of how to utilize `script`, `editorScript`, `viewScript`, `style`, and `editorStyle` and what the difference between the different script keys are.

In either case, I still think we need to make sure that it's clear that if you're using `entry` to define your block assets, you need to have `block` in the entry key. Otherwise, for older projects that are utilizing `entry` for blocks, there's the potential for a lot of time to be wasted when an engineer can't figure out why their block's editor styles aren't compiling (guess how I know 😅 ).

I'm also curious why it is that scripts build properly without `block` in the entry key, but stylesheets don't?

Happy to chat about it over a call if that makes more sense 🙂
