### ISSUE TITLE
Recommendations on installation of `@wordpress` packages when using dependency extraction plugin

### ISSUE THREAD

**Issue by johnwatkins0** [10up/10up-toolkit#27]
**Is your enhancement related to a problem? Please describe.**

When using the dependency extraction plugin on a project, we don't technically need to install the `@wordpress` packages we're using because they're loaded from core. 

The 10up Eslint config tells us that these packages need to be installed, however. If we don't install them, we see CLI warnings (and editor warnings if you're using an ESLint extension). 

<img width="939" alt="Screen Shot 2021-04-02 at 5 58 07 PM" src="https://user-images.githubusercontent.com/9020968/113460064-138d1280-93dd-11eb-9c37-8a9b8e19141e.png">

My personal preference is to install these packages as dev dependencies so I can use autocompletion in my editor. I suspect many other engineers would want to avoid installing dependencies just for the editor benefit, though.

**Describe the solution you'd like**

Either:
1. Guidance in the README with recommendations on how to approach these dependencies in our projects.
2. A rule in the 10up Eslint config to ignore uninstalled `@wordpress` packages.

**Designs**

**Describe alternatives you've considered**

**Additional context**

**Comment by nicholasio** [comment]
The WordPress eslint config has a rule ignoring `@wordpress` packages: https://github.com/10up/eslint-config/blob/trunk/wordpress.js#L14 but that's for the unresolved rule.

It doesn't seem to be possible to ignore the `import/no-extraneous-dependencies` rule for specific globs patterns but I like your suggestion to install them as dev deps to get autocompletion! I think that should be the route we go.

**Comment by tlovett1** [comment]
Seems like a lot of packages we'd have to install.

**Comment by johnwatkins0** [comment]
It does become a lot. On a project where I've installed just the packages we use for some Gutenberg blocks and other admin stuff, it's 18 different `@wordpress` packages. I do find it hard to justify recommending this approach because of the extra time it takes to install the packages and the time it adds to CI workflows. While it's my preferred approach, there's definitely a maintenance cost. Having a linting rule to make the whole question moot would be ideal.

**Comment by nicholasio** [comment]
I was wrong - we can ignore certain paths: https://github.com/benmosher/eslint-plugin-import#importignore we can also make the WordPress packages be treated as "core modules" https://github.com/benmosher/eslint-plugin-import#importcore-modules

Seems like the easiest solution

**Comment by nicholasio** [comment]
Had to manually add all wordpress packages as core modules: https://github.com/10up/eslint-config/pull/37

Will release a new version of the eslint config and include it in 10up scripts

**Comment by johnwatkins0** [comment]
Thanks @nicholasio. Closing this.
