### ISSUE TITLE
Breaking out of WP Dependencies for Linters

### ISSUE THREAD

**Issue by Antonio-Laguna** [10up/10up-toolkit#295]
Coming from https://github.com/10up/10up-toolkit/issues/284

**Comment by Antonio-Laguna** [comment]
> Like @nicholasio, I can also see the advantages of making the toolkit framework agnostic. That said, it's very based around WP as it stands, and my concern with breaking that out would be making it more difficult for engineers to get up and running with it.

@darylldoyle I don't think this makes it harder for engineers to get up and running and I'm not personally suggesting to break out and do a different thing. We can be aligned but not be tied by those dependencies.

My proposed solution was more in line with:

* Remove wp packages
* Clone their rules
* Use https://www.npmjs.com/package/stylelint-stylistic as I suggested to WP too so deprecated rules are kept and we can keep linting CSS.
* Continue business as usual

With toolkit, the idea is to be as far from disruptive as possible when it comes to a major upgrade. If we go this way for Stylelint this means the only major change is that you're now using Stylelint 15 but you don't have to change anything in your code or the way you code moving forward.

**Comment by fabiankaegy** [comment]
Question: Which dependencies exactly are we talking about?

If this is only about stylelint I don't see any issues with that. 

If we propose to drop all `@wordpress` packages used in toolkit I would be against that. 

`@wordpress/dependency-extraction-webpack-plugin` for example has major benefits :)

**Comment by Antonio-Laguna** [comment]
@fabiankaegy mostly Stylelint and probably also eslint in the near future. It's just we get constrained with other tooling.

**Comment by nicholasio** [comment]
While 10up-toolkit can be used outside of the WordPress context, its main use case is definitely WordPress so it does make sense to use the relevant `@wordpress` packages. However, eslint-config, stylelint-config and even the babel-config are used in many contexts that are not wp-related and therefore it makes sense for these packages not to have WP dependencies.

Originally, I didn't go with the wp eslint config for several reasons:
- It was a WP package and we would use it outside of WP context
- It had a prettier fork
- Its js rules were non standard for the JS community.

**Comment by darylldoyle** [comment]
Got it. I thought the idea was to remove WP dependencies from toolkit and then have a separate config that could be used for WP builds. If that's not the case and it's just for linting, then I have no issues 🙂

**Comment by nicholasio** [comment]
Closing this as we have come to a decision on this that was already implemented in other PRs.
