### ISSUE TITLE
Why not use @wordpress/scripts?

### ISSUE THREAD

**Issue by kimmenbert** [10up/10up-toolkit#296]
### Describe your question

Hey, Hope it's OK for me to post this here, not a 10up employee.

We've been using @wordpress/scripts for theme and plugins assets compiling for a while now, with a minor adjusted Webpack config to add multiple (dynamic) entry-points and outputs.

What is the reasoning for you to make this build tool that mimics @wordpress/scripts by the look of it?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nicholasio** [comment]
Hi @kimmenbert we have made several changes to support the way we do things here at 10up. There are quite a few things we're doing differently. We also use 10up-toolkit on non-wordpress project so while 10up-toolkit is mainly targeting WordPress projects it also includes things that `@wordpress/scripts` do not for these types of projects.

10up-toolkit is used across most projects at 10up and it also helps us to provide consistent tooling and experience to our engineering team.
