### ISSUE TITLE
Custom Css entry points produce .assets.php file in dist/js folder

### ISSUE THREAD

**Issue by fabiankaegy** [10up/10up-toolkit#3]
**Is your enhancement related to a problem? Please describe.**
When using custom entry points defined in the package.json css files generate an `.asset.php` file that is located in the `dist/js` folder.

```json
"@10up/scripts": {
    "entry": {
        "example": "./assets/css/example/example.css"
    }
```

leads to the list folder looking like:

```
dist
    - js
         - example.assets.php 
    - css
         - example.css 
```

**Comment by tlovett1** [comment]
Good catch. I fixed this one
