### ISSUE TITLE
Importing a JSON file from node_modules results in `Module not found` error.

### ISSUE THREAD

**Issue by derweili** [10up/10up-toolkit#307]
### Describe the bug

When importing a JSON file from a package located in `node_modules` the build process fails with: 

```
Module not found: Error: Can't resolve 'd3-time-format/locale/de-DE.json' in '{...}/assets/js/frontend/components/poll-of-polls'
resolve 'd3-time-format/locale/de-DE.json' in '{...}/assets/js/frontend/components/poll-of-polls'
  Parsed request is a module
```

It seams that while generating the paths to resolve the file, the `.json` extension is not recognized but additional extensions are appended.

<details>
  <summary>See full error message</summary>
  <pre>
ERROR in ./assets/js/frontend/components/poll-of-polls/poll-of-polls.js 3:0-55
Module not found: Error: Can't resolve 'd3-time-format/locale/de-DE.json' in '{root_folder}/wordpress/wp-content/themes/{theme_name}/assets/js/frontend/components/poll-of-polls'
resolve 'd3-time-format/locale/de-DE.json' in '{root_folder}/wordpress/wp-content/themes/{theme_name}/assets/js/frontend/components/poll-of-polls'
  Parsed request is a module
  using description file: {root_folder}/wordpress/wp-content/themes/{theme_name}/package.json (relative path: ./assets/js/frontend/components/poll-of-polls)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      {root_folder}/wordpress/wp-content/themes/{theme_name}/assets/js/frontend/components/poll-of-polls/node_modules doesn't exist or is not a directory
      {root_folder}/wordpress/wp-content/themes/{theme_name}/assets/js/frontend/components/node_modules doesn't exist or is not a directory
      {root_folder}/wordpress/wp-content/themes/{theme_name}/assets/js/frontend/node_modules doesn't exist or is not a directory
      {root_folder}/wordpress/wp-content/themes/{theme_name}/assets/js/node_modules doesn't exist or is not a directory
      {root_folder}/wordpress/wp-content/themes/{theme_name}/assets/node_modules doesn't exist or is not a directory
      looking for modules in {root_folder}/wordpress/wp-content/themes/{theme_name}/node_modules
        existing directory {root_folder}/wordpress/wp-content/themes/{theme_name}/node_modules/d3-time-format
          using description file: {root_folder}/wordpress/wp-content/themes/{theme_name}/node_modules/d3-time-format/package.json (relative path: .)
            using exports field: ./locale/de-DE.json.json
              using description file: {root_folder}/wordpress/wp-content/themes/{theme_name}/node_modules/d3-time-format/package.json (relative path: ./locale/de-DE.json.json)
                no extension
                  Field 'browser' doesn't contain a valid alias configuration
                  {root_folder}/wordpress/wp-content/themes/{theme_name}/node_modules/d3-time-format/locale/de-DE.json.json doesn't exist
                .tsx
                  Field 'browser' doesn't contain a valid alias configuration
                  {root_folder}/wordpress/wp-content/themes/{theme_name}/node_modules/d3-time-format/locale/de-DE.json.json.tsx doesn't exist
                .ts
                  Field 'browser' doesn't contain a valid alias configuration
                  {root_folder}/wordpress/wp-content/themes/{theme_name}/node_modules/d3-time-format/locale/de-DE.json.json.ts doesn't exist
                .js
                  Field 'browser' doesn't contain a valid alias configuration
                  {root_folder}/wordpress/wp-content/themes/{theme_name}/node_modules/d3-time-format/locale/de-DE.json.json.js doesn't exist
                as directory
                  {root_folder}/wordpress/wp-content/themes/{theme_name}/node_modules/d3-time-format/locale/de-DE.json.json doesn't exist
      {root_folder}/wordpress/wp-content/themes/node_modules doesn't exist or is not a directory
      {root_folder}/wordpress/wp-content/node_modules doesn't exist or is not a directory
      {root_folder}/wordpress/node_modules doesn't exist or is not a directory
      {root_folder}/node_modules doesn't exist or is not a directory
      /Users/my_user/wp-local-docker-sites/node_modules doesn't exist or is not a directory
      /Users/my_user/node_modules doesn't exist or is not a directory
      /Users/node_modules doesn't exist or is not a directory
      /node_modules doesn't exist or is not a directory
  </pre>
</details>

Importing the JSON file without extension works.
This error only occurs when importing JSON files from node_modules.
When importing JSON files from outside of `node_modules`, the opposite behaviour applies. With `.json` extension works, without extension fails.

I think a consistent behaviour for importing JSON files would be great.

### Steps to Reproduce

1. Install `d3-time-format` package. `npm i d3-time-format@4.1.0`
2. Import the locale JSON files
```
import * as fr from 'd3-time-format/locale/fr-FR.json';
import * as de from 'd3-time-format/locale/de-DE.json';
```
3. Run the build process. You will receive the error mentioned above.
4. Import the JSON files without extension
```
import * as fr from 'd3-time-format/locale/fr-FR';
import * as de from 'd3-time-format/locale/de-DE';
```
5. Run the build process. Build will succeed this time.

### Screenshots, screen recording, code snippet

<img width="531" alt="Bildschirmfoto 2023-07-12 um 16 00 53" src="https://github.com/10up/10up-toolkit/assets/6911678/6f081b94-31b5-4c9f-8e61-f24873d3a2e9">

### Environment information

- Device: MacBook
- OS: macOS 13.4.1

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nicholasio** [comment]
Thanks for the report - I wonder if we need to add json extension here https://github.com/10up/10up-toolkit/blob/develop/packages/toolkit/config/webpack/resolve.js#L3C3-L3C3

**Comment by nicholasio** [comment]
@derweili I think this is by d3's design.

if you look at the package.json of `d3-time-format` is has the follow `exports` config.

```js
  "exports": {
    ".": {
      "umd": "./dist/d3-time-format.min.js",
      "default": "./src/index.js"
    },
    "./locale/*": "./locale/*.json"
  },
```

Therefore anything you import from `locale` subpath should not have the json extension as it is added automatically.
