### ISSUE TITLE
postcss-editor-styles does not correctly wrap styles

### ISSUE THREAD

**Issue by ryanwelcher** [10up/10up-toolkit#31]
**Describe the bug**
When using the default `postcss.config.js` provided by 10up/scripts, editor-style.css is generated but none of the selectors are wrapped with `.editor-styles-wrapper ` as expected. 

I was able to address this by changing  https://github.com/10up/10up-scripts/blob/trunk/config/postcss.config.js#L11 to be a function that receives `file`:

```js
'postcss-editor-styles': file =>
      file.basename === 'editor-style.css'
        ? {
            scopeTo: '.editor-styles-wrapper',
            ignore: [
              ':root',
              '.edit-post-visual-editor.editor-styles-wrapper',
              '.wp-toolbar',
            ],
            remove: ['html', ':disabled', '[readonly]', '[disabled]'],
            tags: ['button', 'input', 'label', 'select', 'textarea', 'form'],
          }
        : false,
```

**Steps to Reproduce**

1. Add 10up/scripts to a project
2. Create an entryoint with the file name being editor-style.css i. e `"editor-style": "./assets/css/admin/editor-style.css",`
3. Run the `start` or `build` command
4. Styles are compiled by not scoped as expected.

**Expected behavior**
Styles should be scoped to `.editor-styles-wrapper`

**Screenshots**

**Environment information**
 - Device: 
 - OS: 
 - Browser and version: 
 - WordPress version: 
 
 - Plugins and version: 
 - Theme and version: 
 
 - <details><summary>Site Health Info:</summary>
   
   </details>

**Additional context**

**Comment by nicholasio** [comment]
The fix makes sense to me. Are you working on a PR? if not I can get this one fixed.

**Comment by ryanwelcher** [comment]
I'll have a PR in place tomorrow.
