### ISSUE TITLE
Conflicting stylelint rules prevent usage of `currentcolor`

### ISSUE THREAD

**Issue by derweili** [10up/10up-toolkit#315]
### Describe the bug

We currently have two conflicting stylelint rules that prevent usage of `currentcolor`/`currentColor`:

**Example 1**
```css
color: currentColor;
```
Results in this error: `Expected "currentColor" to be "currentcolor" (value-keyword-case)`

**Example 2**
```css
color: currentcolor;
```
Error: `Expected variable, function or keyword for "currentcolor" of "color" (scale-unlimited/declaration-strict-value)` 
This is because `scale-unlimited/declaration-strict-value` only allows `currentColor`, [see here](https://github.com/10up/10up-toolkit/blob/aa19110fe2c2186c61d87c25cc0e979393352780/packages/stylelint-config/index.js#L7).

To fix this, we should change `currentColor` to `currentcolor` in the stylelint-config:
https://github.com/10up/10up-toolkit/blob/aa19110fe2c2186c61d87c25cc0e979393352780/packages/stylelint-config/index.js#L7

### Steps to Reproduce

1. use the example from above
2. run stylelint

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Antonio-Laguna** [comment]
This is fixed by #298
