### ISSUE TITLE
Upgrade `@10up/eslint-config` to `eslint-plugin-prettier v5`

### ISSUE THREAD

**Issue by orballo** [10up/10up-toolkit#322]
### Is your enhancement related to a problem? Please describe.

Apparently there is an [incompatibility](https://stackoverflow.com/questions/76624993/prettier-3-0-0-typeerror-prettier-resolveconfig-sync-is-not-a-function) between `prettier v3` and `eslint-plugin-prettier v4`, which makes `eslint` fail.

```
Oops! Something went wrong! :(

ESLint: 8.46.0

TypeError: prettier.getFileInfo.sync is not a function
```

`prettier v3` is automatically installed because there are several libraries setting it as a dependency with `>=`.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nicholasio** [comment]
Yes! The workaround now is to pin prettier to a specific version in your project. In the next major we plan to declare prettier as peer dep only and have projects opt into the specific version of Prettier they want to use
