### ISSUE TITLE
Add extensions and settings for VSCode

### ISSUE THREAD

**Issue by ncoetzer** [10up/10up-toolkit#324]
### Is your enhancement related to a problem? Please describe.

Adding a `.vscode` directory to the scaffold with `extensions.json` and `settings.json` could help align our code editors to format code the same. For example, indent spacing issues on pull requests will be reduced or even avoided.

### Describe alternatives you've considered

One alternative that is currently in progress is a 10up VSCode Extension Pack. The repo can be accessed [here](https://github.com/10up/vscode-setup).

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nicholasio** [comment]
@ncoetzer Just checking to see if you had time to look into this.

**Comment by ncoetzer** [comment]
> @ncoetzer Just checking to see if you had time to look into this.

@nicholasio Sorry, have been a little crazy lately between projects. I have it on my list for this week. Aiming to work on it Friday.
