### ISSUE TITLE
Compiled JavaScript contains arrow functions

### ISSUE THREAD

**Issue by rdimascio** [10up/10up-toolkit#34]
**Describe the bug**
By default, the generated runtime code contains ES6 arrow functions. To test this, in my entry file, I have a simple `class` declaration and instance —

```js
class Add {
	constructor(a, b) {
		this.a = a;
		this.b = b;
	}

	add() {
		return this.a + this.b;
	}
}

const test = new Add(1, 2);
console.log(test.add());
```

When I build this, the `class` syntax is transpiled properly to use prototypes, but it's wrapped in an IIFE that uses an arrow function —

```js
(()=>{"use strict";function n(n,e){ ... })();
```

I set up a simple repo to demonstrate this - https://github.com/rdimascio/10up-scripts-test
Here's the entry - https://github.com/rdimascio/10up-scripts-test/blob/master/index.js
Here's the output - https://github.com/rdimascio/10up-scripts-test/blob/master/dist/js/index.js

And if I copy the source code from `@10up/reading-position` into my [entry file](https://github.com/rdimascio/10up-scripts-test/blob/reading-position/index.js) and create an instance, then the [generated code](https://github.com/rdimascio/10up-scripts-test/blob/reading-position/dist/js/index.js) contains 76 arrow functions.

In the Webpack 5 documentation, it's stated [here](https://webpack.js.org/configuration/target/) that `When no information about the target or the environment features is provided, then ES2015 will be used.` Since there is no `browserlist` config that Webpack has access to, it tries to infer the environment from the `target` and `output.environment` properties.

Either adding `target: ['web', 'es5']` or
```js
output: {
    environment: {
        arrowFunctions: false,
    },
},
```
to `webpack.config.js` resolves this issue. As demonstrated [here](https://github.com/rdimascio/10up-scripts-test/blob/fix/webpack-target/webpack.config.js), the [generated code](https://github.com/rdimascio/10up-scripts-test/blob/fix/webpack-target/dist/js/index.js) no longer contains arrow functions.

**Steps to Reproduce**
1. Add 10up/scripts to a project
2. Create an entrypoint with the file name being frontend.js i. e "frontend": "./assets/js/frontend/frontend.js" and add the following code
```js
class Add {
	constructor(a, b) {
		this.a = a;
		this.b = b;
	}

	add() {
		return this.a + this.b;
	}
}

const test = new Add(1, 2);
console.log(test.add());
```
3. Run the start or build command
4. Generated code contains an arrow function.

**Expected behavior**
Generated code should use ES5 syntax.

**Environment information**
 - Device: 
 - OS: 
 - Browser and version: 
 - WordPress version: 
 
 - Plugins and version: 
 - Theme and version: 
 
 - <details><summary>Site Health Info:</summary>
   
   </details>

**Additional context**

**Comment by nicholasio** [comment]
Thanks for the detailed bug report!

It looks like webpack is the culprit and not babel (which was our initial assumption) bc it's wrapping modules in ES6 arrow functions.

We do have a browserlist config in 10up/babel-preset but I don't think webpack can see that. I'll see if there's a way we can have webpack properly infer things from our browserlist config, otherwise we can just set target to `['web', 'es5']`
