### ISSUE TITLE
filenames.config.js can not be customized in project root

### ISSUE THREAD

**Issue by marcoluzi** [10up/10up-toolkit#347]
### Describe the bug

In your README.md, in the section [customizing build paths](https://github.com/10up/10up-toolkit/blob/develop/packages/toolkit/README.md#-customizing-build-paths) it is statet, that the build paths and file names can be changed by placing a filenames.config.js in the project root. It seems like the toolkit is not checking if this file is available in the project root and requires its own default file. [See here](https://github.com/10up/10up-toolkit/blob/08f7c786cedcfd1111a1b41d4e19f008c365bf34/packages/toolkit/utils/config.js#L114C16-L114C16).

I suggest to implement a logic to check for a custom config file, like it is done with the config files for babel, stylelint, webpack etc.

### Steps to Reproduce

1. Create filenames.config.js in the project root.
2. Change filenames.
3. Build the project.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nicholasio** [comment]
That's for the catch I don't know why it wasn't checking for that path... it's not something we used very often so likely why it was overlooked for so long.

**Comment by nicholasio** [comment]
Fixed in #355
