### ISSUE TITLE
SVG and Imagemin. Styling SVG's from within the file

### ISSUE THREAD

**Issue by saltnpixels** [10up/10up-toolkit#56]
**Is your enhancement related to a problem? Please describe.**

in a recent project, I was asked to use svg's as background images.
I needed a way to change their color on hover.

As a background image this was not easily done. 

**Describe the solution you'd like**

After some research i discovered you can put styles inside the svg file itself and based on the url of the svg file it can change the styles.

This is done by adding a hash at the end of the file. (ex: icon-home.svg vs. icon-home.svg#hovered)
Then inside the svg file there can be styles for #hovered:target path{}

See a working example here:

https://codepen.io/saltnpixels/pen/LYWpaoJ

** The Problem **
The problem is svg files that we add to the svg folder get processed by Imagemin on `npm run build`
This strips out any styles added. I have also found it strips ID's sometimes or other things I add for animation. It also removes empty path or g tags and sometimes those are needed for styling.

Is there a way we can either remove the SVG files from Imagemin processing or figure out how to apply options to stop it from touching styles and attributes.

**Comment by nicholasio** [comment]
@joesnellpdx Any thoughts? In the old scaffold, we were also processing svg files. Are svg file sizes typically a concern?

**Comment by nicholasio** [comment]
Discussed with @joesnellpdx and we don't think this needs to be in 10up-toolkit.
