### ISSUE TITLE
BrowserSync not working properly

### ISSUE THREAD

**Issue by saltnpixels** [10up/10up-toolkit#62]
**Describe the bug**
When using npm run watch, if there are file changes made, the entire site refreshes.  
This is normal when changes are made to php or JS files. However CSS files should not cause a full refresh.
It used to inject the CSS without a reload. This was faster.

I believe this is happening because JS/PHP files cause a full reload, and when CSS files are touched, JS/PHP files are being produced. 
Looking in the dist folder there are lots of files for each style file being used as an entry.

So style.css creates a style.js which is not being used..
There are also php files being generated every time a css file is touched too. I'm not sure what is doing that though... or what those are.

Lastly css files aren't actually being watched.

There is a mistake in the webpack plugin.js file 
`dist//**/*.css` should be `dist/**/*.css`

It still works because those js and php files are being touched so it reloads.

**Steps to Reproduce**
Make changes to a css file and watch the browser do a full reload. 
For more testing, edit some text with inspector. It will reload and change.

**Expected behavior**
For CSS, the page should not reload.  

## A fix?

While finding out if those js and php files should be getting created, we can tell browsersync to ignore the files being created in dist in the browsersync options.

`ignore: ['dist/**/*.php', 'dist/**/*.js'],`

The last thing would be to use servestatic.
https://browsersync.io/docs/options#option-serveStatic

but getting those params right seems tricky.

I have been successful before by using the following:

```
new BrowserSyncPlugin(
      {
	      host: 'localhost',
	      port: 3000,
	      proxy: devURL,
	      open: false,
	      files: ['**/*.php', '**/*.js', 'dist/**/*.css'],
	      ignore: ['dist/**/*.php', 'dist/**/*.js'],
	      serveStatic: ['.'],
	      rewriteRules: [
		      {
			      match: /wp-content\/themes\/.*\/dist/g,
			      replace: 'dist'
		      }
	      ]
      },
      {
	      injectCss: true,
	      reload: false,
      },
      ),
```

**Comment by joesnellpdx** [comment]
@nicholasio 

This is still an issue. Your updates (for me) are causing the page to reload on each change (with css) rather than injecting the changes.

If I manually add @saltnpixels recommendations ... the theme works for the css, but not agnostic per the plugin, and JS requires an extra reload.

I spend a few hours here without a definitive resolution, but this is still an issue from what I can tell. 

My best analysis is all files in `dist` are getting updated - not just the css files if only css files are changed - which is triggering the reload.

Also, your updates doesn't include `'dist/**/*.js'`

**Comment by saltcod** [comment]
Seconding Joe's report there, and Eric's solution. I put this in `theme/node_modules/10up-toolkit/config/webpack/plugins.js`

```
new BrowserSyncPlugin(
	{
		host: 'localhost',
		port: 3000,
		proxy: devURL,
		open: false,
		files: ['**/*.php', '**/*.js', 'dist/**/*.css'],
		ignore: ['dist/**/*.php', 'dist/**/*.js'],
		serveStatic: ['.'],
		rewriteRules: [
			{
				match: /wp-content\/themes\/.*\/dist/g,
				replace: 'dist'
			}
		]
	},
	{
		injectCss: true,
		reload: false,
	},
),
```

— 

In related news(?) — I was unable to get this working from `wp-content`. I'm only able to get compiling and browser-syncing  to work if I npm install & npm run watch from the theme.

**Comment by nicholasio** [comment]
I'm closing this in favor of #150 

BrowserSync will be deprecated starting with next release and removed in the next major release.
