### ISSUE TITLE
Missing @wordpress/element dependency when using 10up-toolkit build on non-WP React project

### ISSUE THREAD

**Issue by johnwatkins0** [10up/10up-toolkit#87]
**Describe the bug**

I'm using 10up-toolkit to for the build script in a project that uses React but has nothing to do with WordPress. When running `10up-toolkit build`, all the JS files with react have errors like this:

```
ERROR in ./src/js/examples/select-menu.js 1:0-61
Module not found: Error: Can't resolve '@wordpress/element' in '/Users/johnwatkins/WSI-Design-System/styleguide/src/js/examples'
```

**Expected behavior**

**Screenshots**

**Environment information**
 - Device: 
 - OS: 
 - Browser and version: 
 - WordPress version: 
 
 - Plugins and version: 
 - Theme and version: 
 
 - <details><summary>Site Health Info:</summary>
   
   </details>

**Additional context**

**Comment by nicholasio** [comment]
@johnwatkins0 can you try setting `wordpress` to false? in package.json? or passing `--wp=no` when running the cli?

```
 "10up-toolkit": {
   "wordpress": false
  }
```

You might also be interested in using 10up-toolkit in "package mode", it removes all of the wordpress assumptions, it's focused on building packages that will be published to npm but it essentially works like create-react-app/react scripts 
 so if you project has a single entry point it should work well! 

https://github.com/10up/developer-handbooks/blob/trunk/handbooks/10up-toolkit/04-authoring-libraries.mdx (in progress docs) and https://github.com/10up/developer-handbooks/blob/trunk/handbooks/javascript/03-setting-up-modal-project.mdx

**Comment by johnwatkins0** [comment]
`wordpress: false` fixed it. Thank you. I'll close this.
