### ISSUE TITLE
Multiple click event fire, maybe BrowserSync related

### ISSUE THREAD

**Issue by royboy789** [10up/10up-toolkit#94]
When click event handling, callback fires multiple times. 

Example:
```
document.getElementById('menu-toggle').addEventListener('click', this.toggleMenu, false);
```
The `toggleMenu` will fire multiple times

**Expected behavior**
Event to fire once. This is behavior on non-browsersync'd URL's.
Example: If browsersync sets a proxy to `https://localhost:3000` the main local URL for the WordPress install will not have the same issue.

**Environment information**
 - Device: MacbookPro
 - OS: 11.5
 - Browser and version: Firefox Developer Edition
 - WordPress version: 5.8

**Additional context**
Not sure if browsersync related, just noticing that

**Comment by nicholasio** [comment]
This is definitely a weird one, I don't think we have ever experienced this.

@royboy789 I'm not sure if you're still using 10up-toolkit but have this still been a problem for you?

**Comment by royboy789** [comment]
@nicholasio no, I think it had to do with LocalWP and not the toolkit. Been using the toolkit and upgraded all projects to the latest iteration, and all are working well.

Thank You! closing.
