### ISSUE TITLE
Favicon.ico isn't moved to dist

### ISSUE THREAD

**Issue by darylldoyle** [10up/10up-toolkit#96]
In line below, `ico` files aren't added which means that `favicon.ico` files are never moved into the `dist` directory.

https://github.com/10up/10up-toolkit/blob/304e0cae491f25380f3909c19557258f6a8fcb2d/packages/toolkit/config/webpack/plugins.js#L54

**Comment by nicholasio** [comment]
I'm not sure if this is really necessary. Any specific reasons we'd prefer referencing the favicon from the dist folder instead of the source folder?

In JS apps in general (and this is true when running 10up-toolking in package mode) things like this would live in the public folder.
